name: Build and Push Docker image to Docker Hub

on: push
jobs:
    push_to_registry:
        name: Push multi image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
            
            - name: Login to DH
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DH1USER }}
                password: ${{ secrets.DH1KEY }}
            
            - name: Build and push client image
              uses: docker/build-push-action@v6
              with:
                context: ./client
                push: true
                tags: n1bnft/client:latest

            - name: Build and push api image
              uses: docker/build-push-action@v6
              with:
                context: ./server
                push: true
                tags: n1bnft/server:latest

            - name: Build and push worker image
              uses: docker/build-push-action@v6
              with:
                context: ./worker
                push: true
                tags: n1bnft/worker:latest

            - name: Build and push front nginx image
              uses: docker/build-push-action@v6
              with:
                context: ./nginx
                push: true
                tags: n1bnft/nginx:latest